"""addtional tracking models for admission

Revision ID: ccda595c2f5f
Revises: 7f4039b9036f
Create Date: 2026-01-22 05:05:20.372864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccda595c2f5f'
down_revision: Union[str, None] = '7f4039b9036f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### create admission_consultation_bookings table ###
    op.create_table('admission_consultation_bookings',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('admission_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('consultation_booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['admission_id'], ['admission.id'], name='admission_consultation_bookings_admission_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['consultation_booking_id'], ['consultation_queue.id'], name='admission_consultation_bookings_consultation_booking_id_fkey', ondelete='CASCADE'),
    )

    # ### add admission_prescriptions table ###
    op.create_table('admission_prescription',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('admission_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['admission_id'], ['admission.id'], name='admission_prescription_admission_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['prescription_id'], ['pharmacy_prescription.id'], name='admission_prescription_prescription_id_fkey', ondelete='CASCADE'),
    )

    # ### end admission_lab_services table ###
    op.create_table('admission_lab_services',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('admission_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('lab_service_queue_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['admission_id'], ['admission.id'], name='admission_lab_services_admission_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['lab_service_queue_id'], ['lab_service_queue.id'], name='admission_lab_services_lab_service_queue_id_fkey', ondelete='CASCADE'),
    )

    op.create_table('admission_ward_rooms',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('ward_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('room_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['ward_id'], ['admission_ward.id'], name='ward_rooms_ward_id_fkey', ondelete='CASCADE'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admission_consultation_bookings')
    op.drop_table('admission_prescription')
    op.drop_table('admission_lab_services')
    op.drop_table('admission_ward_rooms')
    # ### end Alembic commands ###
